### ISSUE TITLE
Load Custom Fonts?

### ISSUE THREAD

**Issue by wordyallen** [lean/phaser-es6-webpack#15]
I produced some fonts at font-squirrel based on a font I had.  eg:

```css
/* Generated by Font Squirrel (http://www.fontsquirrel.com) on January 12, 2016 */
@font-face {
    font-family: 'lintelregular';
    src: url('lintel-regular-webfont.eot');
    src: url('lintel-regular-webfont.eot?#iefix') format('embedded-opentype'),
         url('lintel-regular-webfont.woff2') format('woff2'),
         url('lintel-regular-webfont.woff') format('woff'),
         url('lintel-regular-webfont.ttf') format('truetype'),
         url('lintel-regular-webfont.svg#lintelregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```
The folder also has the font file types.

How do I load that in with webpack? There' font loading and css?  I can't seem to parse any of them.   Would it be better to create a url and load it in as a webfont?

Thanks,
Joe
